// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: proto/sarifpb/sarif.proto

package sarifpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Repository struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	RowId               int32                  `protobuf:"varint,1,opt,name=row_id,json=rowId,proto3" json:"row_id,omitempty"`
	RepositoryFullName  string                 `protobuf:"bytes,2,opt,name=repository_full_name,json=repositoryFullName,proto3" json:"repository_full_name,omitempty"`
	RepositoryUrl       string                 `protobuf:"bytes,3,opt,name=repository_url,json=repositoryUrl,proto3" json:"repository_url,omitempty"`
	AnalysisStatus      string                 `protobuf:"bytes,4,opt,name=analysis_status,json=analysisStatus,proto3" json:"analysis_status,omitempty"`
	ResultCount         *int32                 `protobuf:"varint,5,opt,name=result_count,json=resultCount,proto3,oneof" json:"result_count,omitempty"`
	ArtifactSizeInBytes *int32                 `protobuf:"varint,6,opt,name=artifact_size_in_bytes,json=artifactSizeInBytes,proto3,oneof" json:"artifact_size_in_bytes,omitempty"`
	AnalysisId          string                 `protobuf:"bytes,7,opt,name=analysis_id,json=analysisId,proto3" json:"analysis_id,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Repository) Reset() {
	*x = Repository{}
	mi := &file_proto_sarifpb_sarif_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Repository) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Repository) ProtoMessage() {}

func (x *Repository) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sarifpb_sarif_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Repository.ProtoReflect.Descriptor instead.
func (*Repository) Descriptor() ([]byte, []int) {
	return file_proto_sarifpb_sarif_proto_rawDescGZIP(), []int{0}
}

func (x *Repository) GetRowId() int32 {
	if x != nil {
		return x.RowId
	}
	return 0
}

func (x *Repository) GetRepositoryFullName() string {
	if x != nil {
		return x.RepositoryFullName
	}
	return ""
}

func (x *Repository) GetRepositoryUrl() string {
	if x != nil {
		return x.RepositoryUrl
	}
	return ""
}

func (x *Repository) GetAnalysisStatus() string {
	if x != nil {
		return x.AnalysisStatus
	}
	return ""
}

func (x *Repository) GetResultCount() int32 {
	if x != nil && x.ResultCount != nil {
		return *x.ResultCount
	}
	return 0
}

func (x *Repository) GetArtifactSizeInBytes() int32 {
	if x != nil && x.ArtifactSizeInBytes != nil {
		return *x.ArtifactSizeInBytes
	}
	return 0
}

func (x *Repository) GetAnalysisId() string {
	if x != nil {
		return x.AnalysisId
	}
	return ""
}

type Analysis struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	RowId                int32                  `protobuf:"varint,1,opt,name=row_id,json=rowId,proto3" json:"row_id,omitempty"`
	ToolName             string                 `protobuf:"bytes,2,opt,name=tool_name,json=toolName,proto3" json:"tool_name,omitempty"`
	ToolVersion          *string                `protobuf:"bytes,3,opt,name=tool_version,json=toolVersion,proto3,oneof" json:"tool_version,omitempty"`
	AnalysisId           string                 `protobuf:"bytes,4,opt,name=analysis_id,json=analysisId,proto3" json:"analysis_id,omitempty"`
	ControllerRepo       *string                `protobuf:"bytes,5,opt,name=controller_repo,json=controllerRepo,proto3,oneof" json:"controller_repo,omitempty"`
	Date                 *string                `protobuf:"bytes,6,opt,name=date,proto3,oneof" json:"date,omitempty"`
	State                string                 `protobuf:"bytes,7,opt,name=state,proto3" json:"state,omitempty"`
	QueryLanguage        string                 `protobuf:"bytes,8,opt,name=query_language,json=queryLanguage,proto3" json:"query_language,omitempty"`
	CreatedAt            string                 `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	CompletedAt          *string                `protobuf:"bytes,10,opt,name=completed_at,json=completedAt,proto3,oneof" json:"completed_at,omitempty"`
	Status               string                 `protobuf:"bytes,11,opt,name=status,proto3" json:"status,omitempty"`
	FailureReason        *string                `protobuf:"bytes,12,opt,name=failure_reason,json=failureReason,proto3,oneof" json:"failure_reason,omitempty"`
	ScannedReposCount    int32                  `protobuf:"varint,13,opt,name=scanned_repos_count,json=scannedReposCount,proto3" json:"scanned_repos_count,omitempty"`
	SkippedReposCount    int32                  `protobuf:"varint,14,opt,name=skipped_repos_count,json=skippedReposCount,proto3" json:"skipped_repos_count,omitempty"`
	NotFoundReposCount   int32                  `protobuf:"varint,15,opt,name=not_found_repos_count,json=notFoundReposCount,proto3" json:"not_found_repos_count,omitempty"`
	NoCodeqlDbReposCount int32                  `protobuf:"varint,16,opt,name=no_codeql_db_repos_count,json=noCodeqlDbReposCount,proto3" json:"no_codeql_db_repos_count,omitempty"`
	OverLimitReposCount  int32                  `protobuf:"varint,17,opt,name=over_limit_repos_count,json=overLimitReposCount,proto3" json:"over_limit_repos_count,omitempty"`
	ActionsWorkflowRunId int32                  `protobuf:"varint,18,opt,name=actions_workflow_run_id,json=actionsWorkflowRunId,proto3" json:"actions_workflow_run_id,omitempty"`
	TotalReposCount      int32                  `protobuf:"varint,19,opt,name=total_repos_count,json=totalReposCount,proto3" json:"total_repos_count,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *Analysis) Reset() {
	*x = Analysis{}
	mi := &file_proto_sarifpb_sarif_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Analysis) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Analysis) ProtoMessage() {}

func (x *Analysis) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sarifpb_sarif_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Analysis.ProtoReflect.Descriptor instead.
func (*Analysis) Descriptor() ([]byte, []int) {
	return file_proto_sarifpb_sarif_proto_rawDescGZIP(), []int{1}
}

func (x *Analysis) GetRowId() int32 {
	if x != nil {
		return x.RowId
	}
	return 0
}

func (x *Analysis) GetToolName() string {
	if x != nil {
		return x.ToolName
	}
	return ""
}

func (x *Analysis) GetToolVersion() string {
	if x != nil && x.ToolVersion != nil {
		return *x.ToolVersion
	}
	return ""
}

func (x *Analysis) GetAnalysisId() string {
	if x != nil {
		return x.AnalysisId
	}
	return ""
}

func (x *Analysis) GetControllerRepo() string {
	if x != nil && x.ControllerRepo != nil {
		return *x.ControllerRepo
	}
	return ""
}

func (x *Analysis) GetDate() string {
	if x != nil && x.Date != nil {
		return *x.Date
	}
	return ""
}

func (x *Analysis) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *Analysis) GetQueryLanguage() string {
	if x != nil {
		return x.QueryLanguage
	}
	return ""
}

func (x *Analysis) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Analysis) GetCompletedAt() string {
	if x != nil && x.CompletedAt != nil {
		return *x.CompletedAt
	}
	return ""
}

func (x *Analysis) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Analysis) GetFailureReason() string {
	if x != nil && x.FailureReason != nil {
		return *x.FailureReason
	}
	return ""
}

func (x *Analysis) GetScannedReposCount() int32 {
	if x != nil {
		return x.ScannedReposCount
	}
	return 0
}

func (x *Analysis) GetSkippedReposCount() int32 {
	if x != nil {
		return x.SkippedReposCount
	}
	return 0
}

func (x *Analysis) GetNotFoundReposCount() int32 {
	if x != nil {
		return x.NotFoundReposCount
	}
	return 0
}

func (x *Analysis) GetNoCodeqlDbReposCount() int32 {
	if x != nil {
		return x.NoCodeqlDbReposCount
	}
	return 0
}

func (x *Analysis) GetOverLimitReposCount() int32 {
	if x != nil {
		return x.OverLimitReposCount
	}
	return 0
}

func (x *Analysis) GetActionsWorkflowRunId() int32 {
	if x != nil {
		return x.ActionsWorkflowRunId
	}
	return 0
}

func (x *Analysis) GetTotalReposCount() int32 {
	if x != nil {
		return x.TotalReposCount
	}
	return 0
}

type Rule struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	RowId           int32                  `protobuf:"varint,1,opt,name=row_id,json=rowId,proto3" json:"row_id,omitempty"`
	Id              string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	RuleName        string                 `protobuf:"bytes,3,opt,name=rule_name,json=ruleName,proto3" json:"rule_name,omitempty"`
	RuleDescription *string                `protobuf:"bytes,4,opt,name=rule_description,json=ruleDescription,proto3,oneof" json:"rule_description,omitempty"`
	PropertyTags    []string               `protobuf:"bytes,5,rep,name=property_tags,json=propertyTags,proto3" json:"property_tags,omitempty"`
	Kind            string                 `protobuf:"bytes,6,opt,name=kind,proto3" json:"kind,omitempty"`
	SeverityLevel   *string                `protobuf:"bytes,7,opt,name=severity_level,json=severityLevel,proto3,oneof" json:"severity_level,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Rule) Reset() {
	*x = Rule{}
	mi := &file_proto_sarifpb_sarif_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Rule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rule) ProtoMessage() {}

func (x *Rule) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sarifpb_sarif_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rule.ProtoReflect.Descriptor instead.
func (*Rule) Descriptor() ([]byte, []int) {
	return file_proto_sarifpb_sarif_proto_rawDescGZIP(), []int{2}
}

func (x *Rule) GetRowId() int32 {
	if x != nil {
		return x.RowId
	}
	return 0
}

func (x *Rule) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Rule) GetRuleName() string {
	if x != nil {
		return x.RuleName
	}
	return ""
}

func (x *Rule) GetRuleDescription() string {
	if x != nil && x.RuleDescription != nil {
		return *x.RuleDescription
	}
	return ""
}

func (x *Rule) GetPropertyTags() []string {
	if x != nil {
		return x.PropertyTags
	}
	return nil
}

func (x *Rule) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Rule) GetSeverityLevel() string {
	if x != nil && x.SeverityLevel != nil {
		return *x.SeverityLevel
	}
	return ""
}

type Alert struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	RowId              int32                  `protobuf:"varint,1,opt,name=row_id,json=rowId,proto3" json:"row_id,omitempty"`
	FilePath           string                 `protobuf:"bytes,2,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	StartLine          *int32                 `protobuf:"varint,3,opt,name=start_line,json=startLine,proto3,oneof" json:"start_line,omitempty"`
	StartColumn        *int32                 `protobuf:"varint,4,opt,name=start_column,json=startColumn,proto3,oneof" json:"start_column,omitempty"`
	EndLine            *int32                 `protobuf:"varint,5,opt,name=end_line,json=endLine,proto3,oneof" json:"end_line,omitempty"`
	EndColumn          *int32                 `protobuf:"varint,6,opt,name=end_column,json=endColumn,proto3,oneof" json:"end_column,omitempty"`
	CodeSnippetSource  *string                `protobuf:"bytes,7,opt,name=code_snippet_source,json=codeSnippetSource,proto3,oneof" json:"code_snippet_source,omitempty"`
	CodeSnippetSink    *string                `protobuf:"bytes,8,opt,name=code_snippet_sink,json=codeSnippetSink,proto3,oneof" json:"code_snippet_sink,omitempty"`
	CodeSnippet        *string                `protobuf:"bytes,9,opt,name=code_snippet,json=codeSnippet,proto3,oneof" json:"code_snippet,omitempty"`
	CodeSnippetContext *string                `protobuf:"bytes,10,opt,name=code_snippet_context,json=codeSnippetContext,proto3,oneof" json:"code_snippet_context,omitempty"`
	Message            string                 `protobuf:"bytes,11,opt,name=message,proto3" json:"message,omitempty"`
	ResultFingerprint  *string                `protobuf:"bytes,12,opt,name=result_fingerprint,json=resultFingerprint,proto3,oneof" json:"result_fingerprint,omitempty"`
	StepCount          *int32                 `protobuf:"varint,13,opt,name=step_count,json=stepCount,proto3,oneof" json:"step_count,omitempty"`
	RepositoryRowId    int32                  `protobuf:"varint,14,opt,name=repository_row_id,json=repositoryRowId,proto3" json:"repository_row_id,omitempty"`
	AnalysisRowId      int32                  `protobuf:"varint,15,opt,name=analysis_row_id,json=analysisRowId,proto3" json:"analysis_row_id,omitempty"`
	RuleRowId          int32                  `protobuf:"varint,16,opt,name=rule_row_id,json=ruleRowId,proto3" json:"rule_row_id,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Alert) Reset() {
	*x = Alert{}
	mi := &file_proto_sarifpb_sarif_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Alert) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Alert) ProtoMessage() {}

func (x *Alert) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sarifpb_sarif_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Alert.ProtoReflect.Descriptor instead.
func (*Alert) Descriptor() ([]byte, []int) {
	return file_proto_sarifpb_sarif_proto_rawDescGZIP(), []int{3}
}

func (x *Alert) GetRowId() int32 {
	if x != nil {
		return x.RowId
	}
	return 0
}

func (x *Alert) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *Alert) GetStartLine() int32 {
	if x != nil && x.StartLine != nil {
		return *x.StartLine
	}
	return 0
}

func (x *Alert) GetStartColumn() int32 {
	if x != nil && x.StartColumn != nil {
		return *x.StartColumn
	}
	return 0
}

func (x *Alert) GetEndLine() int32 {
	if x != nil && x.EndLine != nil {
		return *x.EndLine
	}
	return 0
}

func (x *Alert) GetEndColumn() int32 {
	if x != nil && x.EndColumn != nil {
		return *x.EndColumn
	}
	return 0
}

func (x *Alert) GetCodeSnippetSource() string {
	if x != nil && x.CodeSnippetSource != nil {
		return *x.CodeSnippetSource
	}
	return ""
}

func (x *Alert) GetCodeSnippetSink() string {
	if x != nil && x.CodeSnippetSink != nil {
		return *x.CodeSnippetSink
	}
	return ""
}

func (x *Alert) GetCodeSnippet() string {
	if x != nil && x.CodeSnippet != nil {
		return *x.CodeSnippet
	}
	return ""
}

func (x *Alert) GetCodeSnippetContext() string {
	if x != nil && x.CodeSnippetContext != nil {
		return *x.CodeSnippetContext
	}
	return ""
}

func (x *Alert) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Alert) GetResultFingerprint() string {
	if x != nil && x.ResultFingerprint != nil {
		return *x.ResultFingerprint
	}
	return ""
}

func (x *Alert) GetStepCount() int32 {
	if x != nil && x.StepCount != nil {
		return *x.StepCount
	}
	return 0
}

func (x *Alert) GetRepositoryRowId() int32 {
	if x != nil {
		return x.RepositoryRowId
	}
	return 0
}

func (x *Alert) GetAnalysisRowId() int32 {
	if x != nil {
		return x.AnalysisRowId
	}
	return 0
}

func (x *Alert) GetRuleRowId() int32 {
	if x != nil {
		return x.RuleRowId
	}
	return 0
}

// Wrapper messages for serializing collections
type RepositoryList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Repositories  []*Repository          `protobuf:"bytes,1,rep,name=repositories,proto3" json:"repositories,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RepositoryList) Reset() {
	*x = RepositoryList{}
	mi := &file_proto_sarifpb_sarif_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RepositoryList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepositoryList) ProtoMessage() {}

func (x *RepositoryList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sarifpb_sarif_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepositoryList.ProtoReflect.Descriptor instead.
func (*RepositoryList) Descriptor() ([]byte, []int) {
	return file_proto_sarifpb_sarif_proto_rawDescGZIP(), []int{4}
}

func (x *RepositoryList) GetRepositories() []*Repository {
	if x != nil {
		return x.Repositories
	}
	return nil
}

type AnalysisList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Analyses      []*Analysis            `protobuf:"bytes,1,rep,name=analyses,proto3" json:"analyses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalysisList) Reset() {
	*x = AnalysisList{}
	mi := &file_proto_sarifpb_sarif_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalysisList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalysisList) ProtoMessage() {}

func (x *AnalysisList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sarifpb_sarif_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalysisList.ProtoReflect.Descriptor instead.
func (*AnalysisList) Descriptor() ([]byte, []int) {
	return file_proto_sarifpb_sarif_proto_rawDescGZIP(), []int{5}
}

func (x *AnalysisList) GetAnalyses() []*Analysis {
	if x != nil {
		return x.Analyses
	}
	return nil
}

type RuleList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rules         []*Rule                `protobuf:"bytes,1,rep,name=rules,proto3" json:"rules,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RuleList) Reset() {
	*x = RuleList{}
	mi := &file_proto_sarifpb_sarif_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuleList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuleList) ProtoMessage() {}

func (x *RuleList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sarifpb_sarif_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuleList.ProtoReflect.Descriptor instead.
func (*RuleList) Descriptor() ([]byte, []int) {
	return file_proto_sarifpb_sarif_proto_rawDescGZIP(), []int{6}
}

func (x *RuleList) GetRules() []*Rule {
	if x != nil {
		return x.Rules
	}
	return nil
}

type AlertList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Alerts        []*Alert               `protobuf:"bytes,1,rep,name=alerts,proto3" json:"alerts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AlertList) Reset() {
	*x = AlertList{}
	mi := &file_proto_sarifpb_sarif_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlertList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlertList) ProtoMessage() {}

func (x *AlertList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sarifpb_sarif_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlertList.ProtoReflect.Descriptor instead.
func (*AlertList) Descriptor() ([]byte, []int) {
	return file_proto_sarifpb_sarif_proto_rawDescGZIP(), []int{7}
}

func (x *AlertList) GetAlerts() []*Alert {
	if x != nil {
		return x.Alerts
	}
	return nil
}

var File_proto_sarifpb_sarif_proto protoreflect.FileDescriptor

const file_proto_sarifpb_sarif_proto_rawDesc = "" +
	"\n" +
	"\x19proto/sarifpb/sarif.proto\x12\x05sarif\"\xd4\x02\n" +
	"\n" +
	"Repository\x12\x15\n" +
	"\x06row_id\x18\x01 \x01(\x05R\x05rowId\x120\n" +
	"\x14repository_full_name\x18\x02 \x01(\tR\x12repositoryFullName\x12%\n" +
	"\x0erepository_url\x18\x03 \x01(\tR\rrepositoryUrl\x12'\n" +
	"\x0fanalysis_status\x18\x04 \x01(\tR\x0eanalysisStatus\x12&\n" +
	"\fresult_count\x18\x05 \x01(\x05H\x00R\vresultCount\x88\x01\x01\x128\n" +
	"\x16artifact_size_in_bytes\x18\x06 \x01(\x05H\x01R\x13artifactSizeInBytes\x88\x01\x01\x12\x1f\n" +
	"\vanalysis_id\x18\a \x01(\tR\n" +
	"analysisIdB\x0f\n" +
	"\r_result_countB\x19\n" +
	"\x17_artifact_size_in_bytes\"\xcb\x06\n" +
	"\bAnalysis\x12\x15\n" +
	"\x06row_id\x18\x01 \x01(\x05R\x05rowId\x12\x1b\n" +
	"\ttool_name\x18\x02 \x01(\tR\btoolName\x12&\n" +
	"\ftool_version\x18\x03 \x01(\tH\x00R\vtoolVersion\x88\x01\x01\x12\x1f\n" +
	"\vanalysis_id\x18\x04 \x01(\tR\n" +
	"analysisId\x12,\n" +
	"\x0fcontroller_repo\x18\x05 \x01(\tH\x01R\x0econtrollerRepo\x88\x01\x01\x12\x17\n" +
	"\x04date\x18\x06 \x01(\tH\x02R\x04date\x88\x01\x01\x12\x14\n" +
	"\x05state\x18\a \x01(\tR\x05state\x12%\n" +
	"\x0equery_language\x18\b \x01(\tR\rqueryLanguage\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\tR\tcreatedAt\x12&\n" +
	"\fcompleted_at\x18\n" +
	" \x01(\tH\x03R\vcompletedAt\x88\x01\x01\x12\x16\n" +
	"\x06status\x18\v \x01(\tR\x06status\x12*\n" +
	"\x0efailure_reason\x18\f \x01(\tH\x04R\rfailureReason\x88\x01\x01\x12.\n" +
	"\x13scanned_repos_count\x18\r \x01(\x05R\x11scannedReposCount\x12.\n" +
	"\x13skipped_repos_count\x18\x0e \x01(\x05R\x11skippedReposCount\x121\n" +
	"\x15not_found_repos_count\x18\x0f \x01(\x05R\x12notFoundReposCount\x126\n" +
	"\x18no_codeql_db_repos_count\x18\x10 \x01(\x05R\x14noCodeqlDbReposCount\x123\n" +
	"\x16over_limit_repos_count\x18\x11 \x01(\x05R\x13overLimitReposCount\x125\n" +
	"\x17actions_workflow_run_id\x18\x12 \x01(\x05R\x14actionsWorkflowRunId\x12*\n" +
	"\x11total_repos_count\x18\x13 \x01(\x05R\x0ftotalReposCountB\x0f\n" +
	"\r_tool_versionB\x12\n" +
	"\x10_controller_repoB\a\n" +
	"\x05_dateB\x0f\n" +
	"\r_completed_atB\x11\n" +
	"\x0f_failure_reason\"\x87\x02\n" +
	"\x04Rule\x12\x15\n" +
	"\x06row_id\x18\x01 \x01(\x05R\x05rowId\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x1b\n" +
	"\trule_name\x18\x03 \x01(\tR\bruleName\x12.\n" +
	"\x10rule_description\x18\x04 \x01(\tH\x00R\x0fruleDescription\x88\x01\x01\x12#\n" +
	"\rproperty_tags\x18\x05 \x03(\tR\fpropertyTags\x12\x12\n" +
	"\x04kind\x18\x06 \x01(\tR\x04kind\x12*\n" +
	"\x0eseverity_level\x18\a \x01(\tH\x01R\rseverityLevel\x88\x01\x01B\x13\n" +
	"\x11_rule_descriptionB\x11\n" +
	"\x0f_severity_level\"\xb0\x06\n" +
	"\x05Alert\x12\x15\n" +
	"\x06row_id\x18\x01 \x01(\x05R\x05rowId\x12\x1b\n" +
	"\tfile_path\x18\x02 \x01(\tR\bfilePath\x12\"\n" +
	"\n" +
	"start_line\x18\x03 \x01(\x05H\x00R\tstartLine\x88\x01\x01\x12&\n" +
	"\fstart_column\x18\x04 \x01(\x05H\x01R\vstartColumn\x88\x01\x01\x12\x1e\n" +
	"\bend_line\x18\x05 \x01(\x05H\x02R\aendLine\x88\x01\x01\x12\"\n" +
	"\n" +
	"end_column\x18\x06 \x01(\x05H\x03R\tendColumn\x88\x01\x01\x123\n" +
	"\x13code_snippet_source\x18\a \x01(\tH\x04R\x11codeSnippetSource\x88\x01\x01\x12/\n" +
	"\x11code_snippet_sink\x18\b \x01(\tH\x05R\x0fcodeSnippetSink\x88\x01\x01\x12&\n" +
	"\fcode_snippet\x18\t \x01(\tH\x06R\vcodeSnippet\x88\x01\x01\x125\n" +
	"\x14code_snippet_context\x18\n" +
	" \x01(\tH\aR\x12codeSnippetContext\x88\x01\x01\x12\x18\n" +
	"\amessage\x18\v \x01(\tR\amessage\x122\n" +
	"\x12result_fingerprint\x18\f \x01(\tH\bR\x11resultFingerprint\x88\x01\x01\x12\"\n" +
	"\n" +
	"step_count\x18\r \x01(\x05H\tR\tstepCount\x88\x01\x01\x12*\n" +
	"\x11repository_row_id\x18\x0e \x01(\x05R\x0frepositoryRowId\x12&\n" +
	"\x0fanalysis_row_id\x18\x0f \x01(\x05R\ranalysisRowId\x12\x1e\n" +
	"\vrule_row_id\x18\x10 \x01(\x05R\truleRowIdB\r\n" +
	"\v_start_lineB\x0f\n" +
	"\r_start_columnB\v\n" +
	"\t_end_lineB\r\n" +
	"\v_end_columnB\x16\n" +
	"\x14_code_snippet_sourceB\x14\n" +
	"\x12_code_snippet_sinkB\x0f\n" +
	"\r_code_snippetB\x17\n" +
	"\x15_code_snippet_contextB\x15\n" +
	"\x13_result_fingerprintB\r\n" +
	"\v_step_count\"G\n" +
	"\x0eRepositoryList\x125\n" +
	"\frepositories\x18\x01 \x03(\v2\x11.sarif.RepositoryR\frepositories\";\n" +
	"\fAnalysisList\x12+\n" +
	"\banalyses\x18\x01 \x03(\v2\x0f.sarif.AnalysisR\banalyses\"-\n" +
	"\bRuleList\x12!\n" +
	"\x05rules\x18\x01 \x03(\v2\v.sarif.RuleR\x05rules\"1\n" +
	"\tAlertList\x12$\n" +
	"\x06alerts\x18\x01 \x03(\v2\f.sarif.AlertR\x06alertsBRZ5github.com/ghas-projects/sarif-protobuf/proto/sarifpb\xaa\x02\x18MRVA.Reports.Data.Modelsb\x06proto3"

var (
	file_proto_sarifpb_sarif_proto_rawDescOnce sync.Once
	file_proto_sarifpb_sarif_proto_rawDescData []byte
)

func file_proto_sarifpb_sarif_proto_rawDescGZIP() []byte {
	file_proto_sarifpb_sarif_proto_rawDescOnce.Do(func() {
		file_proto_sarifpb_sarif_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_sarifpb_sarif_proto_rawDesc), len(file_proto_sarifpb_sarif_proto_rawDesc)))
	})
	return file_proto_sarifpb_sarif_proto_rawDescData
}

var file_proto_sarifpb_sarif_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_sarifpb_sarif_proto_goTypes = []any{
	(*Repository)(nil),     // 0: sarif.Repository
	(*Analysis)(nil),       // 1: sarif.Analysis
	(*Rule)(nil),           // 2: sarif.Rule
	(*Alert)(nil),          // 3: sarif.Alert
	(*RepositoryList)(nil), // 4: sarif.RepositoryList
	(*AnalysisList)(nil),   // 5: sarif.AnalysisList
	(*RuleList)(nil),       // 6: sarif.RuleList
	(*AlertList)(nil),      // 7: sarif.AlertList
}
var file_proto_sarifpb_sarif_proto_depIdxs = []int32{
	0, // 0: sarif.RepositoryList.repositories:type_name -> sarif.Repository
	1, // 1: sarif.AnalysisList.analyses:type_name -> sarif.Analysis
	2, // 2: sarif.RuleList.rules:type_name -> sarif.Rule
	3, // 3: sarif.AlertList.alerts:type_name -> sarif.Alert
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_sarifpb_sarif_proto_init() }
func file_proto_sarifpb_sarif_proto_init() {
	if File_proto_sarifpb_sarif_proto != nil {
		return
	}
	file_proto_sarifpb_sarif_proto_msgTypes[0].OneofWrappers = []any{}
	file_proto_sarifpb_sarif_proto_msgTypes[1].OneofWrappers = []any{}
	file_proto_sarifpb_sarif_proto_msgTypes[2].OneofWrappers = []any{}
	file_proto_sarifpb_sarif_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_sarifpb_sarif_proto_rawDesc), len(file_proto_sarifpb_sarif_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_sarifpb_sarif_proto_goTypes,
		DependencyIndexes: file_proto_sarifpb_sarif_proto_depIdxs,
		MessageInfos:      file_proto_sarifpb_sarif_proto_msgTypes,
	}.Build()
	File_proto_sarifpb_sarif_proto = out.File
	file_proto_sarifpb_sarif_proto_goTypes = nil
	file_proto_sarifpb_sarif_proto_depIdxs = nil
}
