// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: proto/sarifpb/sarif.proto

package sarifpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Repository struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RepositoryId   int32                  `protobuf:"varint,1,opt,name=repository_id,json=repositoryId,proto3" json:"repository_id,omitempty"`
	RepositoryName string                 `protobuf:"bytes,2,opt,name=repository_name,json=repositoryName,proto3" json:"repository_name,omitempty"`
	RepositoryUrl  string                 `protobuf:"bytes,3,opt,name=repository_url,json=repositoryUrl,proto3" json:"repository_url,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Repository) Reset() {
	*x = Repository{}
	mi := &file_proto_sarifpb_sarif_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Repository) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Repository) ProtoMessage() {}

func (x *Repository) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sarifpb_sarif_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Repository.ProtoReflect.Descriptor instead.
func (*Repository) Descriptor() ([]byte, []int) {
	return file_proto_sarifpb_sarif_proto_rawDescGZIP(), []int{0}
}

func (x *Repository) GetRepositoryId() int32 {
	if x != nil {
		return x.RepositoryId
	}
	return 0
}

func (x *Repository) GetRepositoryName() string {
	if x != nil {
		return x.RepositoryName
	}
	return ""
}

func (x *Repository) GetRepositoryUrl() string {
	if x != nil {
		return x.RepositoryUrl
	}
	return ""
}

type Run struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RunId          int32                  `protobuf:"varint,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	ToolName       string                 `protobuf:"bytes,2,opt,name=tool_name,json=toolName,proto3" json:"tool_name,omitempty"`
	ToolVersion    *string                `protobuf:"bytes,3,opt,name=tool_version,json=toolVersion,proto3,oneof" json:"tool_version,omitempty"`
	AnalysisId     string                 `protobuf:"bytes,4,opt,name=analysis_id,json=analysisId,proto3" json:"analysis_id,omitempty"`
	ControllerRepo *string                `protobuf:"bytes,5,opt,name=controller_repo,json=controllerRepo,proto3,oneof" json:"controller_repo,omitempty"`
	Date           *string                `protobuf:"bytes,6,opt,name=date,proto3,oneof" json:"date,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Run) Reset() {
	*x = Run{}
	mi := &file_proto_sarifpb_sarif_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Run) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Run) ProtoMessage() {}

func (x *Run) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sarifpb_sarif_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Run.ProtoReflect.Descriptor instead.
func (*Run) Descriptor() ([]byte, []int) {
	return file_proto_sarifpb_sarif_proto_rawDescGZIP(), []int{1}
}

func (x *Run) GetRunId() int32 {
	if x != nil {
		return x.RunId
	}
	return 0
}

func (x *Run) GetToolName() string {
	if x != nil {
		return x.ToolName
	}
	return ""
}

func (x *Run) GetToolVersion() string {
	if x != nil && x.ToolVersion != nil {
		return *x.ToolVersion
	}
	return ""
}

func (x *Run) GetAnalysisId() string {
	if x != nil {
		return x.AnalysisId
	}
	return ""
}

func (x *Run) GetControllerRepo() string {
	if x != nil && x.ControllerRepo != nil {
		return *x.ControllerRepo
	}
	return ""
}

func (x *Run) GetDate() string {
	if x != nil && x.Date != nil {
		return *x.Date
	}
	return ""
}

type Rule struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	RuleId          int32                  `protobuf:"varint,1,opt,name=rule_id,json=ruleId,proto3" json:"rule_id,omitempty"`
	Id              string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	RuleName        string                 `protobuf:"bytes,3,opt,name=rule_name,json=ruleName,proto3" json:"rule_name,omitempty"`
	RuleDescription *string                `protobuf:"bytes,4,opt,name=rule_description,json=ruleDescription,proto3,oneof" json:"rule_description,omitempty"`
	PropertyTags    []string               `protobuf:"bytes,5,rep,name=property_tags,json=propertyTags,proto3" json:"property_tags,omitempty"`
	Kind            string                 `protobuf:"bytes,6,opt,name=kind,proto3" json:"kind,omitempty"`
	SeverityLevel   *string                `protobuf:"bytes,7,opt,name=severity_level,json=severityLevel,proto3,oneof" json:"severity_level,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Rule) Reset() {
	*x = Rule{}
	mi := &file_proto_sarifpb_sarif_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Rule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rule) ProtoMessage() {}

func (x *Rule) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sarifpb_sarif_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rule.ProtoReflect.Descriptor instead.
func (*Rule) Descriptor() ([]byte, []int) {
	return file_proto_sarifpb_sarif_proto_rawDescGZIP(), []int{2}
}

func (x *Rule) GetRuleId() int32 {
	if x != nil {
		return x.RuleId
	}
	return 0
}

func (x *Rule) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Rule) GetRuleName() string {
	if x != nil {
		return x.RuleName
	}
	return ""
}

func (x *Rule) GetRuleDescription() string {
	if x != nil && x.RuleDescription != nil {
		return *x.RuleDescription
	}
	return ""
}

func (x *Rule) GetPropertyTags() []string {
	if x != nil {
		return x.PropertyTags
	}
	return nil
}

func (x *Rule) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Rule) GetSeverityLevel() string {
	if x != nil && x.SeverityLevel != nil {
		return *x.SeverityLevel
	}
	return ""
}

type Alert struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	AlertId            int32                  `protobuf:"varint,1,opt,name=alert_id,json=alertId,proto3" json:"alert_id,omitempty"`
	FilePath           string                 `protobuf:"bytes,2,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	StartLine          *int32                 `protobuf:"varint,3,opt,name=start_line,json=startLine,proto3,oneof" json:"start_line,omitempty"`
	StartColumn        *int32                 `protobuf:"varint,4,opt,name=start_column,json=startColumn,proto3,oneof" json:"start_column,omitempty"`
	EndLine            *int32                 `protobuf:"varint,5,opt,name=end_line,json=endLine,proto3,oneof" json:"end_line,omitempty"`
	EndColumn          *int32                 `protobuf:"varint,6,opt,name=end_column,json=endColumn,proto3,oneof" json:"end_column,omitempty"`
	CodeSnippetSource  *string                `protobuf:"bytes,7,opt,name=code_snippet_source,json=codeSnippetSource,proto3,oneof" json:"code_snippet_source,omitempty"`
	CodeSnippetSink    *string                `protobuf:"bytes,8,opt,name=code_snippet_sink,json=codeSnippetSink,proto3,oneof" json:"code_snippet_sink,omitempty"`
	CodeSnippet        *string                `protobuf:"bytes,9,opt,name=code_snippet,json=codeSnippet,proto3,oneof" json:"code_snippet,omitempty"`
	CodeSnippetContext *string                `protobuf:"bytes,10,opt,name=code_snippet_context,json=codeSnippetContext,proto3,oneof" json:"code_snippet_context,omitempty"`
	Message            string                 `protobuf:"bytes,11,opt,name=message,proto3" json:"message,omitempty"`
	ResultFingerprint  *string                `protobuf:"bytes,12,opt,name=result_fingerprint,json=resultFingerprint,proto3,oneof" json:"result_fingerprint,omitempty"`
	StepCount          *int32                 `protobuf:"varint,13,opt,name=step_count,json=stepCount,proto3,oneof" json:"step_count,omitempty"`
	RepositoryId       int32                  `protobuf:"varint,14,opt,name=repository_id,json=repositoryId,proto3" json:"repository_id,omitempty"`
	AnalysisId         int32                  `protobuf:"varint,15,opt,name=analysis_id,json=analysisId,proto3" json:"analysis_id,omitempty"`
	RuleId             int32                  `protobuf:"varint,16,opt,name=rule_id,json=ruleId,proto3" json:"rule_id,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Alert) Reset() {
	*x = Alert{}
	mi := &file_proto_sarifpb_sarif_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Alert) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Alert) ProtoMessage() {}

func (x *Alert) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sarifpb_sarif_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Alert.ProtoReflect.Descriptor instead.
func (*Alert) Descriptor() ([]byte, []int) {
	return file_proto_sarifpb_sarif_proto_rawDescGZIP(), []int{3}
}

func (x *Alert) GetAlertId() int32 {
	if x != nil {
		return x.AlertId
	}
	return 0
}

func (x *Alert) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *Alert) GetStartLine() int32 {
	if x != nil && x.StartLine != nil {
		return *x.StartLine
	}
	return 0
}

func (x *Alert) GetStartColumn() int32 {
	if x != nil && x.StartColumn != nil {
		return *x.StartColumn
	}
	return 0
}

func (x *Alert) GetEndLine() int32 {
	if x != nil && x.EndLine != nil {
		return *x.EndLine
	}
	return 0
}

func (x *Alert) GetEndColumn() int32 {
	if x != nil && x.EndColumn != nil {
		return *x.EndColumn
	}
	return 0
}

func (x *Alert) GetCodeSnippetSource() string {
	if x != nil && x.CodeSnippetSource != nil {
		return *x.CodeSnippetSource
	}
	return ""
}

func (x *Alert) GetCodeSnippetSink() string {
	if x != nil && x.CodeSnippetSink != nil {
		return *x.CodeSnippetSink
	}
	return ""
}

func (x *Alert) GetCodeSnippet() string {
	if x != nil && x.CodeSnippet != nil {
		return *x.CodeSnippet
	}
	return ""
}

func (x *Alert) GetCodeSnippetContext() string {
	if x != nil && x.CodeSnippetContext != nil {
		return *x.CodeSnippetContext
	}
	return ""
}

func (x *Alert) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Alert) GetResultFingerprint() string {
	if x != nil && x.ResultFingerprint != nil {
		return *x.ResultFingerprint
	}
	return ""
}

func (x *Alert) GetStepCount() int32 {
	if x != nil && x.StepCount != nil {
		return *x.StepCount
	}
	return 0
}

func (x *Alert) GetRepositoryId() int32 {
	if x != nil {
		return x.RepositoryId
	}
	return 0
}

func (x *Alert) GetAnalysisId() int32 {
	if x != nil {
		return x.AnalysisId
	}
	return 0
}

func (x *Alert) GetRuleId() int32 {
	if x != nil {
		return x.RuleId
	}
	return 0
}

// Wrapper messages for serializing collections
type RepositoryList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Repositories  []*Repository          `protobuf:"bytes,1,rep,name=repositories,proto3" json:"repositories,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RepositoryList) Reset() {
	*x = RepositoryList{}
	mi := &file_proto_sarifpb_sarif_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RepositoryList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepositoryList) ProtoMessage() {}

func (x *RepositoryList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sarifpb_sarif_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepositoryList.ProtoReflect.Descriptor instead.
func (*RepositoryList) Descriptor() ([]byte, []int) {
	return file_proto_sarifpb_sarif_proto_rawDescGZIP(), []int{4}
}

func (x *RepositoryList) GetRepositories() []*Repository {
	if x != nil {
		return x.Repositories
	}
	return nil
}

type RunList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Runs          []*Run                 `protobuf:"bytes,1,rep,name=runs,proto3" json:"runs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunList) Reset() {
	*x = RunList{}
	mi := &file_proto_sarifpb_sarif_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunList) ProtoMessage() {}

func (x *RunList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sarifpb_sarif_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunList.ProtoReflect.Descriptor instead.
func (*RunList) Descriptor() ([]byte, []int) {
	return file_proto_sarifpb_sarif_proto_rawDescGZIP(), []int{5}
}

func (x *RunList) GetRuns() []*Run {
	if x != nil {
		return x.Runs
	}
	return nil
}

type RuleList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rules         []*Rule                `protobuf:"bytes,1,rep,name=rules,proto3" json:"rules,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RuleList) Reset() {
	*x = RuleList{}
	mi := &file_proto_sarifpb_sarif_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuleList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuleList) ProtoMessage() {}

func (x *RuleList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sarifpb_sarif_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuleList.ProtoReflect.Descriptor instead.
func (*RuleList) Descriptor() ([]byte, []int) {
	return file_proto_sarifpb_sarif_proto_rawDescGZIP(), []int{6}
}

func (x *RuleList) GetRules() []*Rule {
	if x != nil {
		return x.Rules
	}
	return nil
}

type AlertList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Alerts        []*Alert               `protobuf:"bytes,1,rep,name=alerts,proto3" json:"alerts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AlertList) Reset() {
	*x = AlertList{}
	mi := &file_proto_sarifpb_sarif_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlertList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlertList) ProtoMessage() {}

func (x *AlertList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sarifpb_sarif_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlertList.ProtoReflect.Descriptor instead.
func (*AlertList) Descriptor() ([]byte, []int) {
	return file_proto_sarifpb_sarif_proto_rawDescGZIP(), []int{7}
}

func (x *AlertList) GetAlerts() []*Alert {
	if x != nil {
		return x.Alerts
	}
	return nil
}

var File_proto_sarifpb_sarif_proto protoreflect.FileDescriptor

const file_proto_sarifpb_sarif_proto_rawDesc = "" +
	"\n" +
	"\x19proto/sarifpb/sarif.proto\x12\x05sarif\"\x81\x01\n" +
	"\n" +
	"Repository\x12#\n" +
	"\rrepository_id\x18\x01 \x01(\x05R\frepositoryId\x12'\n" +
	"\x0frepository_name\x18\x02 \x01(\tR\x0erepositoryName\x12%\n" +
	"\x0erepository_url\x18\x03 \x01(\tR\rrepositoryUrl\"\xf7\x01\n" +
	"\x03Run\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\x05R\x05runId\x12\x1b\n" +
	"\ttool_name\x18\x02 \x01(\tR\btoolName\x12&\n" +
	"\ftool_version\x18\x03 \x01(\tH\x00R\vtoolVersion\x88\x01\x01\x12\x1f\n" +
	"\vanalysis_id\x18\x04 \x01(\tR\n" +
	"analysisId\x12,\n" +
	"\x0fcontroller_repo\x18\x05 \x01(\tH\x01R\x0econtrollerRepo\x88\x01\x01\x12\x17\n" +
	"\x04date\x18\x06 \x01(\tH\x02R\x04date\x88\x01\x01B\x0f\n" +
	"\r_tool_versionB\x12\n" +
	"\x10_controller_repoB\a\n" +
	"\x05_date\"\x89\x02\n" +
	"\x04Rule\x12\x17\n" +
	"\arule_id\x18\x01 \x01(\x05R\x06ruleId\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x1b\n" +
	"\trule_name\x18\x03 \x01(\tR\bruleName\x12.\n" +
	"\x10rule_description\x18\x04 \x01(\tH\x00R\x0fruleDescription\x88\x01\x01\x12#\n" +
	"\rproperty_tags\x18\x05 \x03(\tR\fpropertyTags\x12\x12\n" +
	"\x04kind\x18\x06 \x01(\tR\x04kind\x12*\n" +
	"\x0eseverity_level\x18\a \x01(\tH\x01R\rseverityLevel\x88\x01\x01B\x13\n" +
	"\x11_rule_descriptionB\x11\n" +
	"\x0f_severity_level\"\x9f\x06\n" +
	"\x05Alert\x12\x19\n" +
	"\balert_id\x18\x01 \x01(\x05R\aalertId\x12\x1b\n" +
	"\tfile_path\x18\x02 \x01(\tR\bfilePath\x12\"\n" +
	"\n" +
	"start_line\x18\x03 \x01(\x05H\x00R\tstartLine\x88\x01\x01\x12&\n" +
	"\fstart_column\x18\x04 \x01(\x05H\x01R\vstartColumn\x88\x01\x01\x12\x1e\n" +
	"\bend_line\x18\x05 \x01(\x05H\x02R\aendLine\x88\x01\x01\x12\"\n" +
	"\n" +
	"end_column\x18\x06 \x01(\x05H\x03R\tendColumn\x88\x01\x01\x123\n" +
	"\x13code_snippet_source\x18\a \x01(\tH\x04R\x11codeSnippetSource\x88\x01\x01\x12/\n" +
	"\x11code_snippet_sink\x18\b \x01(\tH\x05R\x0fcodeSnippetSink\x88\x01\x01\x12&\n" +
	"\fcode_snippet\x18\t \x01(\tH\x06R\vcodeSnippet\x88\x01\x01\x125\n" +
	"\x14code_snippet_context\x18\n" +
	" \x01(\tH\aR\x12codeSnippetContext\x88\x01\x01\x12\x18\n" +
	"\amessage\x18\v \x01(\tR\amessage\x122\n" +
	"\x12result_fingerprint\x18\f \x01(\tH\bR\x11resultFingerprint\x88\x01\x01\x12\"\n" +
	"\n" +
	"step_count\x18\r \x01(\x05H\tR\tstepCount\x88\x01\x01\x12#\n" +
	"\rrepository_id\x18\x0e \x01(\x05R\frepositoryId\x12\x1f\n" +
	"\vanalysis_id\x18\x0f \x01(\x05R\n" +
	"analysisId\x12\x17\n" +
	"\arule_id\x18\x10 \x01(\x05R\x06ruleIdB\r\n" +
	"\v_start_lineB\x0f\n" +
	"\r_start_columnB\v\n" +
	"\t_end_lineB\r\n" +
	"\v_end_columnB\x16\n" +
	"\x14_code_snippet_sourceB\x14\n" +
	"\x12_code_snippet_sinkB\x0f\n" +
	"\r_code_snippetB\x17\n" +
	"\x15_code_snippet_contextB\x15\n" +
	"\x13_result_fingerprintB\r\n" +
	"\v_step_count\"G\n" +
	"\x0eRepositoryList\x125\n" +
	"\frepositories\x18\x01 \x03(\v2\x11.sarif.RepositoryR\frepositories\")\n" +
	"\aRunList\x12\x1e\n" +
	"\x04runs\x18\x01 \x03(\v2\n" +
	".sarif.RunR\x04runs\"-\n" +
	"\bRuleList\x12!\n" +
	"\x05rules\x18\x01 \x03(\v2\v.sarif.RuleR\x05rules\"1\n" +
	"\tAlertList\x12$\n" +
	"\x06alerts\x18\x01 \x03(\v2\f.sarif.AlertR\x06alertsB3Z1github.com/ghas-projects/sarif-avro/proto/sarifpbb\x06proto3"

var (
	file_proto_sarifpb_sarif_proto_rawDescOnce sync.Once
	file_proto_sarifpb_sarif_proto_rawDescData []byte
)

func file_proto_sarifpb_sarif_proto_rawDescGZIP() []byte {
	file_proto_sarifpb_sarif_proto_rawDescOnce.Do(func() {
		file_proto_sarifpb_sarif_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_sarifpb_sarif_proto_rawDesc), len(file_proto_sarifpb_sarif_proto_rawDesc)))
	})
	return file_proto_sarifpb_sarif_proto_rawDescData
}

var file_proto_sarifpb_sarif_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_sarifpb_sarif_proto_goTypes = []any{
	(*Repository)(nil),     // 0: sarif.Repository
	(*Run)(nil),            // 1: sarif.Run
	(*Rule)(nil),           // 2: sarif.Rule
	(*Alert)(nil),          // 3: sarif.Alert
	(*RepositoryList)(nil), // 4: sarif.RepositoryList
	(*RunList)(nil),        // 5: sarif.RunList
	(*RuleList)(nil),       // 6: sarif.RuleList
	(*AlertList)(nil),      // 7: sarif.AlertList
}
var file_proto_sarifpb_sarif_proto_depIdxs = []int32{
	0, // 0: sarif.RepositoryList.repositories:type_name -> sarif.Repository
	1, // 1: sarif.RunList.runs:type_name -> sarif.Run
	2, // 2: sarif.RuleList.rules:type_name -> sarif.Rule
	3, // 3: sarif.AlertList.alerts:type_name -> sarif.Alert
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_sarifpb_sarif_proto_init() }
func file_proto_sarifpb_sarif_proto_init() {
	if File_proto_sarifpb_sarif_proto != nil {
		return
	}
	file_proto_sarifpb_sarif_proto_msgTypes[1].OneofWrappers = []any{}
	file_proto_sarifpb_sarif_proto_msgTypes[2].OneofWrappers = []any{}
	file_proto_sarifpb_sarif_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_sarifpb_sarif_proto_rawDesc), len(file_proto_sarifpb_sarif_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_sarifpb_sarif_proto_goTypes,
		DependencyIndexes: file_proto_sarifpb_sarif_proto_depIdxs,
		MessageInfos:      file_proto_sarifpb_sarif_proto_msgTypes,
	}.Build()
	File_proto_sarifpb_sarif_proto = out.File
	file_proto_sarifpb_sarif_proto_goTypes = nil
	file_proto_sarifpb_sarif_proto_depIdxs = nil
}
